"""initial_schema

Revision ID: 6dcea77ab8f0
Revises: 
Create Date: 2026-04-07 13:49:30.927546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dcea77ab8f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_event_hash', sa.String(length=64), nullable=False),
    sa.Column('decision_context_json', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'sequence', name='uq_engagement_sequence')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_id'), ['event_id'], unique=True)

    op.create_table('evidence_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_index_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_index_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_index_evidence_id'), ['evidence_id'], unique=True)

    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('asset_ref', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('vuln_ref', sa.String(length=256), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('exploitability', sa.String(length=32), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=256), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('evidence_ids_json', sa.Text(), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'fingerprint', name='uq_eng_fingerprint')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_finding_id'), ['finding_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_findings_fingerprint'), ['fingerprint'], unique=False)

    op.create_table('recon_hosts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('os_guess', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'ip_address', name='uq_eng_ip')
    )
    with op.batch_alter_table('recon_hosts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recon_hosts_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recon_hosts_host_id'), ['host_id'], unique=True)

    op.create_table('recon_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('host_id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'port', 'protocol', name='uq_host_port_proto')
    )
    with op.batch_alter_table('recon_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recon_services_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recon_services_host_id'), ['host_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recon_services_service_id'), ['service_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recon_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recon_services_service_id'))
        batch_op.drop_index(batch_op.f('ix_recon_services_host_id'))
        batch_op.drop_index(batch_op.f('ix_recon_services_engagement_id'))

    op.drop_table('recon_services')
    with op.batch_alter_table('recon_hosts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recon_hosts_host_id'))
        batch_op.drop_index(batch_op.f('ix_recon_hosts_engagement_id'))

    op.drop_table('recon_hosts')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_findings_finding_id'))
        batch_op.drop_index(batch_op.f('ix_findings_engagement_id'))

    op.drop_table('findings')
    with op.batch_alter_table('evidence_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_index_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_index_engagement_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_index_action_id'))

    op.drop_table('evidence_index')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_engagement_id'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
