"""add_approval_tickets

Revision ID: 7c9029fd340a
Revises: 6dcea77ab8f0
Create Date: 2026-04-07 15:11:03.054813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9029fd340a'
down_revision: Union[str, Sequence[str], None] = '6dcea77ab8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_tickets',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('impact_preview', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    with op.batch_alter_table('approval_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_tickets_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_tickets_engagement_id'), ['engagement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_tickets_engagement_id'))
        batch_op.drop_index(batch_op.f('ix_approval_tickets_action_id'))

    op.drop_table('approval_tickets')
    # ### end Alembic commands ###
